# Generated by Django 6.1.1 on 2026-09-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen / General Public'), ('ranger', 'Forest Ranger / Wildlife Authority'), ('admin', 'Platform Administrator')], default='citizen', max_length=20),
        ),
    ]
