# Generated by Django 6.1.1 on 2026-09-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy (on active assignment)'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Ranger base latitude (decimal degrees)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Ranger base longitude (decimal degrees)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registered_location',
            field=models.CharField(blank=True, help_text="Ranger's registered operational town/city (e.g. Kollam)", max_length=150, null=True),
        ),
    ]
