# Generated by Django 6.1.1 on 2026-09-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_availability_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name as per official records', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen / General Public'), ('ranger', 'Forest Ranger (Field Responder)'), ('authority', 'Authority Officer (Dispatch & Verification)'), ('admin', 'Platform Administrator')], default='citizen', max_length=20),
        ),
    ]
