# Generated by Django 5.2.17 on 2026-08-29 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Snake Sighting', max_length=200)),
                ('original_image', models.ImageField(upload_to='sightings/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed_sightings/')),
                ('latitude', models.FloatField(help_text='Latitude in decimal degrees')),
                ('longitude', models.FloatField(help_text='Longitude in decimal degrees')),
                ('location_name', models.CharField(help_text='Street, District, or Landmark Name', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending AI & Authority Verification'), ('VERIFIED', 'Verified Sighting'), ('REJECTED', 'Rejected / False Alarm'), ('RESOLVED', 'Captured / Area Cleared')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_detected', models.BooleanField(default=False)),
                ('species_predicted', models.CharField(blank=True, max_length=150, null=True)),
                ('common_name', models.CharField(blank=True, max_length=150, null=True)),
                ('venom_category', models.CharField(choices=[('HIGHLY_VENOMOUS', 'Highly Venomous'), ('VENOMOUS', 'Venomous'), ('NON_VENOMOUS', 'Non-Venomous')], default='NON_VENOMOUS', max_length=30)),
                ('toxicity_level', models.CharField(default='SAFE', max_length=50)),
                ('danger_score', models.IntegerField(default=10)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, help_text='Additional observer details', null=True)),
                ('authority_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
