# Generated by Django 5.2.17 on 2026-08-30 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingreport',
            name='assigned_responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='duplicate_flag',
            field=models.BooleanField(default=False, help_text='Flagged as potential duplicate sighting'),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='reports.sightingreport'),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='response_status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Responder Assigned'), ('IN_PROGRESS', 'Response in Progress'), ('RESOLVED', 'Captured / Resolved')], default='UNASSIGNED', max_length=20),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='spam_flag',
            field=models.BooleanField(default=False, help_text='Flagged as suspicious/spam submission'),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='spam_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
