# Generated by Django 5.2.17 on 2026-09-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_sightingreport_assigned_responder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingreport',
            name='model_1_name',
            field=models.CharField(default='Snake Detection.v2-model_snake-detection-2.yolov8', max_length=150),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='model_2_name',
            field=models.CharField(default='venom_watch_cnn2_keras', max_length=150),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='snake_confidence',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='snake_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='venom_confidence',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='venomous',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
