# Generated by Django 6.1.1 on 2026-09-25 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_sightingreport_model_1_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightingreport',
            name='model_1_name',
            field=models.CharField(default='venomwatch_cnn2_final (CNN)', max_length=150),
        ),
        migrations.CreateModel(
            name='RangerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the ranger accepted or declined', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'On the way'), ('AT_LOCATION', 'At location'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20)),
                ('distance_km', models.FloatField(blank=True, help_text='Haversine distance from ranger base to report at assignment time', null=True)),
                ('outcome', models.CharField(blank=True, choices=[('SNAKE_CAPTURED', 'Snake Captured'), ('SNAKE_ESCAPED', 'Snake Escaped'), ('SNAKE_NOT_FOUND', 'Snake Not Found'), ('FALSE_REPORT', 'False Report'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('notes', models.TextField(blank=True, help_text='Ranger field notes captured at completion', null=True)),
                ('outcome_image', models.ImageField(blank=True, null=True, upload_to='assignment_outcomes/')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('ranger', models.ForeignKey(limit_choices_to={'profile__role': 'ranger'}, on_delete=django.db.models.deletion.PROTECT, related_name='ranger_assignments', to=settings.AUTH_USER_MODEL)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranger_assignments', to='reports.sightingreport')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
