# Generated by Django 5.2.17 on 2026-08-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(help_text='Emergency Contact / Hotline', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('anti_venom_available', models.BooleanField(default=True)),
                ('anti_venom_stock_vials', models.IntegerField(default=50, help_text='Vials in stock')),
                ('has_icu', models.BooleanField(default=True, help_text='24/7 ICU & Ventilator availability')),
                ('operating_hours', models.CharField(default='24/7 Emergency Care', max_length=100)),
            ],
        ),
    ]
